<?php
return array(
	'BE' => array(
		'installToolPassword' => 'bacb98acf97e0b6112b1d1b650b84971',
	),
	'DB' => array(
		'database' => 'c25connectyou',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => 'web2.webshell.de',
		'password' => 'x5ums!99O',
		'username' => 'c25hugifalkner',
	),
	'EXT' => array(
		'extConf' => array(
			'connectyou' => 'a:0:{}',
			'extension_builder' => 'a:3:{s:15:"enableRoundtrip";s:0:"";s:15:"backupExtension";s:1:"1";s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";}',
		),
		'extListArray' => array(
			'introduction',
			'perm',
			'func',
			'filelist',
			'about',
			'version',
			'tsconfig_help',
			'context_help',
			'extra_page_cm_options',
			'impexp',
			'sys_note',
			'tstemplate',
			'tstemplate_ceditor',
			'tstemplate_info',
			'tstemplate_objbrowser',
			'tstemplate_analyzer',
			'func_wizards',
			'wizard_crpages',
			'wizard_sortpages',
			'lowlevel',
			'install',
			'belog',
			'beuser',
			'aboutmodules',
			'setup',
			'taskcenter',
			'info_pagetsconfig',
			'viewpage',
			'rtehtmlarea',
			'css_styled_content',
			't3skin',
			't3editor',
			'reports',
			'felogin',
			'form',
			'extension_builder',
		),
	),
	'SYS' => array(
		'compat_version' => '6.1',
		'encryptionKey' => '4fee3538693fd9856b643b4cdc079ef4c54fce66aee4120a9eef31c61e1873053586a0ad6be10226c9535f59d682fead',
		'sitename' => 'New TYPO3 site',
	),
);
?>