<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "connectyou"
 *
 * Auto generated by Extension Builder 2014-01-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Connect You',
	'description' => 'Connect You ',
	'category' => 'plugin',
	'author' => 'Dominik Falkner',
	'author_email' => 'falkner.dominik@gmail.com',
	'author_company' => 'BBS-Rohrbach',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>